arenas:
  sumo1:
    world: duels
    kit: SUMO
    spawn1: 61645.62319172236,56.0,661567.5631526835,179.55058,6.4500203
    spawn2: 61645.547732355844,56.0,661555.2271044047,1.5006216,2.2500196
    pos1: 61612.0,17.0,661513.0,0.0,0.0
    pos2: 61684.0,126.0,661626.0,0.0,0.0
  sumo2:
    world: duels
    kit: SUMO
    spawn1: 61645.35198180458,64.0,66167.73089026732,179.5495,4.650024
    spawn2: 61645.61743738153,64.0,66155.32252265752,359.0994,4.50002
    pos1: 61614.0,39.0,66131.0,0.0,0.0
    pos2: 61686.0,112.0,66197.0,0.0,0.0
  soup1:
    world: duels
    kit: SOUP
    spawn1: 61620.846378805225,29.0,6669.934855569616,-180.45,1.8000247
    spawn2: 61620.82023654284,29.0,6640.59273620183,0.74997836,2.1000216
    pos1: 61570.0,16.0,6605.0,0.0,0.0
    pos2: 61654.0,79.0,6727.0,0.0,0.0
  uhc:
    world: duels
    kit: UHC
    spawn1: 61621.742152419756,30.0,694.8454555197686,180.2984,4.049895
    spawn2: 61621.83856258264,30.0,642.6641688013259,2.248291,3.1498923
    pos1: 61584.0,7.0,593.0,0.0,0.0
    pos2: 61657.0,94.0,727.0,0.0,0.0
  boxing:
    world: duels
    kit: BOXING
    spawn1: 61624.37918839389,28.0,139.43578366044616,180.2992,5.6998944
    spawn2: 61623.10116774453,28.0,89.75785193301755,-1.9507815,-1.9500965
    pos1: 61583.0,13.0,57.0,0.0,0.0
    pos2: 61649.0,71.0,169.0,0.0,0.0
  build1:
    world: duels
    kit: BUILD
    spawn1: 56136.88539461241,35.0,6176.071200244759,359.39987,1.7999161
    spawn2: 56137.07970241439,35.0,6232.4635770207615,183.14987,-1.4999866
    pos1: 56100.0,9.0,6152.0,0.0,0.0
    pos2: 56179.0,97.0,6266.0,0.0,0.0
  build2:
    world: duels
    kit: BUILD
    spawn1: 56137.29531217726,28.0,61669.92163072616,357.1485,1.0499107
    spawn2: 56136.99687620497,28.0,61715.42766521759,181.1983,0.14993164
    pos1: 56095.0,4.0,61637.0,0.0,0.0
    pos2: 56176.0,89.0,61768.0,0.0,0.0
mysql:
  host: host
  port: 3306
  database: geral
  user: user
  password: "senha"
